---
restylers:
  - astyle:
      arguments: ["--options=astylerc"]
      exclude:
        - "src/osx_*"
  - clang-format:
      image: restyled/restyler-clang-format:v16.0.6
      include:
        - "**/*.cc"
        - "**/*.hh"
        - "src/osx_*"
  - prettier
