Document: toxic
Title: Debian toxic Manual
Author: <insert document author here>
Abstract: This manual describes what toxic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/toxic/toxic.sgml.gz

Format: postscript
Files: /usr/share/doc/toxic/toxic.ps.gz

Format: text
Files: /usr/share/doc/toxic/toxic.text.gz

Format: HTML
Index: /usr/share/doc/toxic/html/index.html
Files: /usr/share/doc/toxic/html/*.html
