name: checks

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize, milestoned]
  pull_request_target:
    branches: [master]

jobs:
  checks:
    uses: TokTok/ci-tools/.github/workflows/check-release.yml@master
