name: draft

on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
    types: [opened, reopened, synchronize]

# Cancel old builds when pushing new commits.
concurrency:
  group: draft-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: TokTok/ci-tools/.github/workflows/release-drafter.yml@master
